name: time_manager_core
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  # Database
  hive: ^2.2.3
  sembast: ^3.7.4
  localstorage: ^5.0.0

  # Backend
  dio: ^5.7.0
  retrofit: ^4.4.1

  # State Management
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  bloc_concurrency: ^0.2.5

  # Utils
  logger: ^2.4.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  logging: ^1.2.0
  path_provider: ^2.1.4
  path: ^1.9.0
  meta: ^1.15.0
  universal_io: ^2.2.2
  decimal: ^3.0.2
  fpdart: ^1.1.1
  uuid: ^4.5.0
  mime: ^2.0.0
  mime_type: ^1.0.1
  permission_handler: ^11.3.1
  package_info_plus: ^8.3.0

  time_manager_localization:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.2
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
